name:  Run  test
on:
    pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

                      
      - name: Upload a Build Artifact
         
        uses: actions/upload-artifact@v4.4.3
        
      - name: Setup JDK 23

        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug



